### ISSUE TITLE
Deploy a docker registry for empire

### ISSUE THREAD

**Issue by bmarini** [remind101/empire#478]
https://github.com/docker/distribution/blob/master/docs/deploying.md

**Comment by saulshanabrook** [comment]
@bmarini why was this closed?

**Comment by phobologic** [comment]
This was closed because we saw it more as a task for our own internal Empire environment, and not actually a part of the project itself.  It's arguable whether Empire should, as part of the project, have a registry included in it.  For now it seemed like something we didn't believe was core to the project.  That said, it's possible in the future Empire might have it's own registry.

**Comment by saulshanabrook** [comment]
@phobologic So you would say that if you have private images you would recommend uploading them to Dockerhub under a private plan?

**Comment by phobologic** [comment]
@saulshanabrook That, or any other private registry that you trust.  We use dockerhub. Eventually we do plan on having an internal registry, mostly for performance reasons, though honestly those don't hit us very often so we're not in a huge rush to make it happen.
