### ISSUE TITLE
RFC: Documentation Organization

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#545]
This is meant to open up our discussions about the organization of the current documentation to the community, as well as gather ideas on what kind of documentation would be useful to everyone.  Please let us know:

- does this look good?
- is there anything missing?
- is there a particular site/project that you think has amazing documentation?

Thanks!

---

**Overview**
- Features & Design GOALS
- Known Limitations
- Roadmap
- FAQ

**Getting Started**
- Prerequisites
- Quickstart
- Empire in Production - Best Practices
  - Deployment
  - Routing
  - Logging
  - Security

**Users Guide**
- Deploying an application
- Process Management
- Exposing an app publicly
- SSL Certs

**Hacking on Empire**
- Running the tests
- Running Empire Locally
- Contributing Guidelines
- Reporting Bugs
- Reporting Security Vulnerabilities

**Reference**
- Configuration Options
- COMMAND LINE
- Troubleshooting

**Comment by public** [comment]
Sounds like a great start.

**Comment by ekosz** [comment]
@phobologic I think would would be a great addition is recommendation on how to run your distributed application locally. For example Empire does its service discovery via DNS, a section how how to replicate that locally would be awesome.

**Comment by phobologic** [comment]
@ekosz When you say 'run your application locally' do you mean running Empire without ECS?

Replicating something like the service discovery without the benefit of things like ECS/ELB/Route53 would be pretty hard.  We use a bit of docker-compose internally, but it's super basic, and not meant to replicate a full production environment.

**Comment by ekosz** [comment]
@phobologic Yeah thats what I meant. How do developers develop without being able to run their applications locally? Can you only test integrations of separate services at the staging level?

What I'm thinking about is that you have a web front-end that serves up a list of products. It may be fetching the products from an inventory service, the signed in user information from another service, and finally product recommendations from the recommendation service.

When working on that web frontend, if you're unable to run those services locally do you just rely on heavy use of mocking those API calls?

**Comment by zachlatta** [comment]
Looks good! Any plans on the timeline of having these docs created? We'd love to experiment with moving some (non critical) applications to Empire in production.

**Comment by ejholmes** [comment]
Hey @ekosz I can explain our development environments a little bit.

Because we have a lot of services, and each one of those services has it's own set of dependencies, we do use a lot of mocking. If you were to setup one of our core services with all of it's dependencies being concrete implementations, it would be a real headache.

For example, we have a service for event tracking, but our developers don't really need to be running that service locally; it wouldn't provide any added value. So, in our code bases, we have interfaces with concrete implementations, and also fake implementations that can be used in tests/development environments.

Our general philosophy is to, by default, use a fake implementation of a dependency in development (not including core dependencies like databases), but make it easy to use a real implementation (e.g. by setting an environment variable).

To answer your question more directly, we're moving our development environments to be `docker-compose` based, so each project has it's own `docker-compose.yml` that's suitable for development. If we want to use a real dependency, then we just pull the docker image in for that service and run it.

An example, for our web client might look like this:

```yml
web:
  build: ./
  links:
    - api
  environment:
    API_URL: http://api
api:
  image: remind101/api
  links:
    - postgres
postgres:
   image: postgres
```

With the majority of the api's dependencies being fake implementations.

Hope that answers your question.

**Comment by ejholmes** [comment]
@zachlatta we're hoping to get some time to flesh out documentation in the next couple of weeks.

**Comment by phobologic** [comment]
Not sure if people get notified about references to issues in github, but just in case - I've just setup #567 - it doesn't add any new content, but sets up the initial structure talked about in here.  Does this seem confusing without more content? There's a lot of TODOs there, but at least it gives us a place we can point at to divide & conquer.

**Comment by ejholmes** [comment]
Gonna close this since it's pretty old.
