### ISSUE TITLE
Provide a way to find the DNS for the ELB of a service

### ISSUE THREAD

**Issue by public** [remind101/empire#556]
Due to ...reasons... (we run ECS on another account from our main platform) we can't use the Route 53 domain names that much in our environment. So we need to use the actual ELB DNS name when communicating with our services. This is a bit ugly but pretty much fine. However currently Empire doesn't make it very easy to get this information, AFAICT I actually have to login to the Amazon console and go and copy and paste the domain name out of that.

It would be very handy if there was a command (`emp info?`) that showed this information.

**Comment by ejholmes** [comment]
Agreed, we've talked about this internally but don't have any immediate plans to add it since it's mostly a minor annoyance for us. One of the primary reasons we haven't done this is because we're not totally sure what this would look like if we supported a Kubernetes backend, or if it would even make sense for Kubernetes. We've kind of just leaned toward little bash scripts wrapping the aws CLI.

We also want to make sure that whatever we do here is supported when we can attach multiple ELB's to an app.

I think if we did implement this, `emp info` would probably be the right place. We could use the [web_url](https://github.com/bgentry/heroku-go/blob/79471b3acc7a331d461bf07de216c45357f143c6/app.go#L66) attribute.
