### ISSUE TITLE
Allow associating multiple security groups with ELBs

### ISSUE THREAD

**Issue by rgabo** [remind101/empire#564]
Would be great if `EMPIRE_ELB_SG_PUBLIC` accepted a comma-separated list of security groups. In our particular case, a `public` and a `default` security group would be associated with internet-facing ELBs:

 * public allows 80/443 ingress
 * default allows unfiltered communication within the VPC public/private subnets (only within instances of the same security group)

If the notation makes sense (same as how subnets are configured with `EMPIRE_EC2_SUBNETS_*`), I can take a stab at this, should be straightforward.

**Comment by phobologic** [comment]
the ELB_SG_PUBLIC (& PRIVATE) security groups are only applied to the ELB's that are created.  They allow:

1. All port 80 & 443 traffic into ELBs created by Empire.
2. All port 9000-10000 traffic from those ELBs to the Minions

These are not applied to the minion hosts themselves, those have another security group that is setup outside of Empire.  So basically it goes:

1. The Minion host security group is created outside of empire.
2. The `EMPIRE_ELB_SG_PUBLIC` & `EMPIRE_ELB_SG_PRIVATE` SGs are created outside of empire and given the access listed above.
3. Public ELB get `EMPIRE_ELB_SG_PUBLIC` applied to them when created by empire.
4. Private ELB get `EMPIRE_ELB_SG_PRIVATE` applied to them when created by empire.

This allows all the access you should need to & from the ELBs & the minion hosts.

Does that make sense?  I think there was some confusion here about where the SGs were getting applied, which again, will hopefully be cleared up in documentation/production stack information.

**Comment by pikeas** [comment]
@phobologic I've been cranking on a production-ready Empire setup - we've exchanged messages on a couple of other GH issues. A couple of comments/questions:

- Why does the internal LB security group accept traffic from 0.0.0.0/0? AFAIK it should only accept traffic from the VPC (10.0.0.0/16 with a default config), or to be even stricter, only from the private subnet/SG?
- Why do the internal LB, external LB and "container instance" (minion) security groups have egress rules? SG rules are stateful, so I believe outbound rules are unnecessary on all of these.
- Why does the minion security group accept traffic on all ports, instead of only 9000-10000 per your description?

Although the provided CloudFormation stack is explicitly marked as not production ready, the security groups and routes should be locked down to the minimal set of permissions which work, or documented when less strict than needed. As is, I'm burning cycles digging through Empire source and GH issues to figure out what's actually necessary for the app to run, so I can properly secure things without breaking functionality.

**Comment by phobologic** [comment]
@pikeas Sorry for the delay, I'm actually out of the country right now on my vacation.  I got a quiet moment though, so let me try to answer your questions.  I actually didn't write the initial CF template, so this'll just be my best guesses.

1. It totally could be tighter, there's no reason the internal ELB SG has to allow from 0.0.0.0 - that was likely just us making it wide open for ease of writing at the time.

2. I'm not sure where you're seeing that - I don't see anything named 'Egress' in my current copy of the cloudformation template, so not sure what you're seeing there :)

3. This is likely a vestigal rule based back when we weren't yet sure what we were going to do for port management.  Really, you should only need 9000-10000 for the ELB->Minion hosts.

I'm back home on Tuesday and one of the things i plan to spend a good chunk of time on is the documentation, so hopefully things will get clearer a lot sooner.

**Comment by phobologic** [comment]
@rgabo Does my initial reply make sense?  Do you still imagine a reason for wanting multiple SGs?

**Comment by pikeas** [comment]
@phobologic Re: egress rules - according to AWS docs, a wide open egress rule is automatically added to all SGs unless explicitly overridden.

I'm looking forward to your docs update!

**Comment by phobologic** [comment]
Ahh - I've never really put a lot of effort into locking down egress rules.  A lot of apps need to access external resources, so the effort of maintaining them (especially on internal only services) was never a huge priority.

I'm going to go ahead and close this issue - I don't think it's necessary any longer.  @rgabo please re-open if you think there's still a need!  Thanks!

**Comment by rgabo** [comment]
Terraform automatically removes the "All Traffic" egress rule and requires you to declare it explicitly if that's your intention. I think this default behavior makes a lot of sense and we do set up both ingress/egress rules as a result.

The original comment and whether multiple SGs are necessary comes down to a simple question of how you organize your SGs:

If you organize them by "nouns", as in "load balancer", "web server", then a single SG will describe what that particular instance or ELB should be allowed to do.

If you organize them by "roles", as in "private", "public", "default", "nat" or even "ssh", "https" then each SG only includes certain set of rules. An ELB in our case has multiple roles:

1. Serves public traffic (Ingress: 80, 443, Egress: None)
2. Talk to other instances in the VPC (wide open inside the VPC)

To follow this SG organization, one would want to associate multiple SGs to the ELBS.

We follow the more granular, "role"-based SG organization and we worked this issue around by having an "elb" SG that covers all ingress/egress rules that the Empire ELBs should have.

I hope that makes (some) sense.

**Comment by phobologic** [comment]
@rgabo Ahhh - that does make sense.  That's actually the first time I've heard of folks using security groups that way!  Out of curiosity, how do you handle source security groups in the method you do SGs?

Basically we have the SGs setup the way you're talking about for your work around:

- Internal ELB SG allows connections from anywhere (internal) on 80 & 443, and can connect to any minion on 9000-10000
- External ELB SG allows connections from anywhere (0.0.0.0/0) on 80 & 443, and can connect to any minion on 9000-10000

Since they're extremely simple rule sets it makes it really easy to manage them.  All Empire does is attach the appropriate SG to the ELB when it is created.

**Comment by pikeas** [comment]
To solve the source group problem, I use noun and role SGs in combination. For example, I have `pg-main` group (ingress <allow-pg-main-out> on 5432) and `allow-pg-main-out` (egress <VPC subnet> on 5432). `allow-pg-main-out` allows access to the whole subnet to prevent a resource dependency cycle.

@phobologic I'm just about done with my Terraform version of Empire. It's more production ready than the provided CF config - separate subnets, bastion/nat, etc - while still being relatively light on resources. Would love to share it with you guys if there's interest?

**Comment by phobologic** [comment]
@pikeas Gotcha.

re: the Terraform configs - I think it'd probably be better if you provided a repo with the Terraform configs in it, and we'd link to it from this repo/the documentation.  The only reason I'm hesitant to host it in this main repo is that none of us @ Remind know Terraform well, and it's unlikely we'll have time to become very acquainted with it - especially not to the point where we could provide great support for it.  I know there are a ton of people who would love to see your work though, so please definitely share them!
