### ISSUE TITLE
Example deploy script for CI

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#575]
Hey,

Was just wondering if you guys could provide a basic example of the deploy process you use to get stuff deployed with your CI.

My main question is around whether you need the 'emp' CLI installed, or if you do it another way.

Cheers

**Comment by ejholmes** [comment]
Hey @gileze33.

We build docker images in Circle CI on every commit, tag it with the git sha and git branch, then push it to the registry. This is all done with a [simple shell script](https://github.com/remind101/docker-build) that we include in every `circle.yml`.

Once we have a docker image for the git commit, we deploy using the GitHub deployments API via a little project called [tugboat](https://github.com/remind101/tugboat). The GH deployments API manages the dirty work of resolving friendly ref's like "master" to a git sha, and tugboat deploys the docker image tagged with that sha. You don't have to use the GH deployments API to deploy though, since you can deploy a docker image with `emp deploy <repo>:<tag>`. You do have to be careful if you deploy a mutable tag like "latest", since updating that tag and restarting ECS services will cause an inadvertent update.

I plan on writing about our build + deploy system on [engineering.remind.com](http://engineering.remind.com/) later, but hopefully that helps.
