### ISSUE TITLE
IAM Role mismatch?

### ISSUE THREAD

**Issue by pikeas** [remind101/empire#579]
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/IAM_policies.html describes the permissions needed for ECS container instances, and for ECS services.

These permission sets do not match the permissions configured in Empire's CF stack.

Amazon instance:
```
ecs:CreateCluster
ecs:DeregisterContainerInstance
ecs:DiscoverPollEndpoint
ecs:Poll
ecs:RegisterContainerInstance
ecs:Submit
```

Empire instance:
```
ec2:Describe*
elasticloadbalancing:*
ecs:*
iam:ListInstanceProfiles
iam:ListRoles
iam:PassRole
route53:*
```

Amazon service:
```
ec2:AuthorizeSecurityGroupIngress
ec2:Describe*
elasticloadbalancing:DeregisterInstancesFromLoadBalancer
elasticloadbalancing:Describe*
elasticloadbalancing:RegisterInstancesWithLoadBalance
```

Empire service:
```
ec2:Describe*
elasticloadbalancing:*
ecs:*
iam:ListInstanceProfiles
iam:ListRoles
iam:PassRole
route53:*
```

These are, shall we say, a bit different. There are (at least) three problems:

1) Empire's permissions are overly broad, using, for example, `ecs:*` instead of enumerating the specific permissions needed as seen in the Amazon config.
2) Empire's service permission set is missing `ec2:AuthorizeSecurityGroupIngress`.
3) Empire's service and instance roles are pulling in `iam` and `route53` permissions which are presumably only used by the controller service, which is being run on the minion cluster. These should be split out into a third, distinct role.

**Comment by ejholmes** [comment]
Hey @pikeas. You're correct, the demo cloudformation has overly broad rules because it runs the controller inside of ECS cluster. Maybe it would be better to spin up two ECS clusters in the demo? One for the controller and one for the minions, so the policies can be split appropriately and more closely match a production environment.

We want to keep the demo environment as easy to debug as possible (and, ideally, as cheap as possible because we also use it for normal development testing) and provide better documentation for production environments. Sorry this is a bit lacking right now.

**Comment by ejholmes** [comment]
Going to close this one out for now, but we should follow up with better docs around what permissions are required for the ECS backend.
