### ISSUE TITLE
Cloudformation template is not working

### ISSUE THREAD

**Issue by windweller** [remind101/empire#594]
I was using the `cloudformation.json` file found here: https://github.com/remind101/empire/blob/master/docs/cloudformation.json to configure a test cluster, but somewhat my creation was not successful and AWS outputs below information:

> The following resource(s) failed to create: [InternalDomain, PubSubnetAz2, PubSubnetAz1, InstanceProfile]. . Rollback requested by user.

I really want to start using empire in a pseudo-production environment.

Since I'm stuck with `cloudformation.json` approach and I followed http://empire.readthedocs.org/en/latest/quickstart_installing/ instructions and failed as well (because it's basically the same cloudformation approach), is there another way for me to create a ECS cluster that Empire can talk to?

**Comment by ejholmes** [comment]
Hi @windweller. Normally when this happens it's because of one of these reasons:

1. You forgot to select a KeyPair when creating the cloudformation stack.
2. The AMI for the ECS Optimized Linux changed.

It doesn't look like Amazon changed the AMI. Can you verify that you selected a keypair when creating the stack?

CloudFormation should also give you details about why the resources failed to create in the Events tab. Could you post that as well?

**Comment by windweller** [comment]
Hi! Thank you for the quick response. I can confirm that I selected a KeyPair when creating the stack. In fact I just tried to launch again, and made sure that I selected a KeyPair, and I still have the same error.

16:09:42 UTC-0400	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	empire-nag-us-east-1	The following resource(s) failed to create: [PubSubnetAz2, PubSubnetAz1, InternalDomain, InstanceProfile, PublicRouteViaIgw]. . Rollback requested by user.
16:09:39 UTC-0400	CREATE_FAILED	AWS::EC2::Route	PublicRouteViaIgw	Resource creation cancelled
16:09:39 UTC-0400	CREATE_FAILED	AWS::Route53::HostedZone	InternalDomain	Resource creation cancelled
16:09:39 UTC-0400	CREATE_FAILED	AWS::IAM::InstanceProfile	InstanceProfile	Resource creation cancelled
16:09:39 UTC-0400	CREATE_FAILED	AWS::EC2::Subnet	PubSubnetAz1	Resource creation cancelled

	15:37:51 UTC-0400	CREATE_FAILED	AWS::EC2::Subnet	PubSubnetAz2	Template error: Fn::Select cannot select nonexistent value at index 1

**Comment by windweller** [comment]
It seems to me the last one is the culprit, and the whole error is created by EC2::Subnet PubSubnet problem.

**Comment by phobologic** [comment]
Can you give us the Parameters that you supplied?  My guess, right now, is that you only supplied a single AZ, and the Cloudformation script requires at least 2.

**Comment by windweller** [comment]
OH!!! Yes. That could very well be the issue! I'll change that now. One more question: it says that the `cloudformation.json` is not for production. Is there a timeline for a more production-ready `cloudformation.json` to be released?

**Comment by phobologic** [comment]
Yeah - there's not a great way, with a comma delimited list in Cloudformation to require a minimum of 2.  The bin/bootstrap method that was listed in the quickstart installing guide figures out which 2 AZs to use for you, unless you manually override it, so that gives us a bit more control.

As of now there's no timeline in place for when we'd have a more production ready Cloudformation template available.  I'm working on creating a set of [stacker](https://github.com/remind101/stacker) blueprints for it that we can release publicly (we use this internally, but it is based on a lot of assumptions that might not make sense for everyone - for example we use ansible for a lot of stuff).  Anyway, I'm hoping we'll have a chance soon - but even then, it's likely just a starting point for most people.

**Comment by windweller** [comment]
OK! Maybe at least the `cloudformation.json` should be changed so it tells people we need to put in two AZs instead of telling `MAX 2` :)
