### ISSUE TITLE
Ability to keep postgres outside of empire?

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#598]
This might completely go against the ethos of empire... But I was just doing some resiliency testing, and went through and killed all of the ECS container instances in the EC2 console. 

It looks like ECS has nicely brought everything back up, but when I go `emp apps` I'm getting nothing back - I'm assuming this is because the postgres container has been recreated from scratch?

Would it be possible to set the postgres URL and use something like RDS to host it?

**Comment by gileze33** [comment]
I'm a pleb - just noticed the `EMPIRE_DATABASE_URL` env variable within the `empire` task in ECS.

Are there any reasons as to why it might be a bad idea to keep the postgres install in RDS rather than inside a container?

**Comment by ejholmes** [comment]
Hey @gileze33. We actually recommend that you use RDS in a production environment. In the demo cloudformation stack, we bring up postgres in a container because RDS takes a good 20-30 minutes to provision.

We have some more docs on production best practices here: http://empire.readthedocs.org/en/latest/production_best_practices/

**Comment by gileze33** [comment]
Awesome, thanks!
