### ISSUE TITLE
Empire Cloud-formation Example HTTP request can't reach

### ISSUE THREAD

**Issue by windweller** [remind101/empire#604]
Hi, I'm still playing with the default Cloud-formation file provided in empire example. Instead of default docker image, I used my own, which is that simple NodeJS docker image with one file: `index.js`

```javascript
var express = require('express');

// Constants
var DEFAULT_PORT = 8080;
var DEFAULT_WHO = "World";
var PORT = process.env.PORT || DEFAULT_PORT;
var WHO = process.env.WHO || DEFAULT_WHO;

// App
var app = express();
app.get('/', function (req, res) {
  res.send('Hello ' + WHO + '. Wish you were here.\n');
});

app.listen(PORT);
console.log('Running on http://localhost:' + PORT);
```

My docker file is (forking from the default git):
```dockerfile
# Originally forked from: git@github.com:gasi/docker-node-hello.git

FROM node:0.10

USER root

ENV AP /data/app

# Application Code
ADD *.js* $AP/

WORKDIR $AP

RUN npm install

EXPOSE 8080

CMD ["node", "index.js"]
```

I uploaded this to my Docker hub, and use empire to upload my image to AWS. I even changed the external ELB's port configuration from simple TCP to both TCP and HTTP (don't know if that's necessary at all):
```
Port Configuration:	
80 (TCP) forwarding to 8080 (TCP)
8080 (HTTP) forwarding to 8080 (HTTP)
Stickiness: Disabled(Edit)
```

However, when I visit DNS record for ELB, I can't see my webpage, it says `404 page not found`. I'm wondering what the problem could be! Can anyone shed some light on it?

**Comment by askreet** [comment]
The ELB exposes the API endpoint, not any browsable portal (that I'm aware
of). You want to install the emp command-line tool and set your
EMPIRE_API_URL environment variable to http://your-elb-dns-name/. Take a
look at the quickstart guide for some examples of the emp tool:

http://empire.readthedocs.org/en/latest/

**Comment by windweller** [comment]
I have already installed emp CLI tool. I'm just wondering how to expose my docker to the Internet

**Comment by phobologic** [comment]
What does emp dynos show?  Is the process staying up?

Which load balancer did you change?  You shouldn't have to change anything in the load balancers that Empire produces (and it would probably break things if you did).

Does your app accept a PORT environment variable and bind to that port?  You'll want it to - or just make sure your app runs on PORT 8080 by default (though you should use the env var route)

Do you have a Procfile?  What's in there?

Look at the events for your service in the ECS console, what is it saying?

Take a look at the load balancer in the AWS console - is does it have any healthy backend instances?  If not, can you tell why?

Also, can you share the exact process that you used to deploy the app inside empire?

**Comment by phobologic** [comment]
BTW, a 404 usually means it's hitting your app - but your app is not serving the page you tried to hit.  Another thing to check is to hop on the host where the container is deployed, then take a look at the docker logs for that container.  You should see the load balancer hitting it for it's health checks, and you'll likely see your requests that are getting the 404.  I don't think ELB returns a 404 ever on it's own.

**Comment by windweller** [comment]
Thank you for looking at this problem :)

1.emp CLI

for some reason, even when I'm under my docker image folder, it says `no apps in git remote`
```
➜  docker-node-hello git:(master) emp ps
error: no apps in git remotes
```
But if I use `emp app`, it shows I have successfully deployed:
```
➜  docker-node-hello git:(master) emp apps
nodedockertest      Jul 19 17:30
```
2.App PORT problem

Since I'm still in the stage of trying out Empire, my app is one single nodeJS file with the same content I posted on the first post. It does listen to 8080 by default, and I don't think I set up any other environment variable. 

```javascript
var express = require('express');

// Constants
var DEFAULT_PORT = 8080;
var DEFAULT_WHO = "World";
var PORT = process.env.PORT || DEFAULT_PORT;
var WHO = process.env.WHO || DEFAULT_WHO;

// App
var app = express();
app.get('/', function (req, res) {
  res.send('Hello ' + WHO + '. Wish you were here.\n');
});

app.listen(PORT);
console.log('Running on http://localhost:' + PORT);
```

3.Procfile

I don't have a Procfile for this project (and I didn't know empire can take a procfile!). The only thing I have is a Dockerfile:
```dockerfile
# Originally forked from: git@github.com:gasi/docker-node-hello.git

FROM node:0.10

USER root

ENV AP /data/app

# Application Code
ADD *.js* $AP/

WORKDIR $AP

RUN npm install

EXPOSE 8080

CMD ["node", "index.js"]
```

4.Event from ECS console
The only event (well it has multiple, but they are all the same) says:
```
7af7373c-61d7-44f1-b04e-61a0b5aa30e6
2015-07-23 07:55:18 -0400
service empir-Servi-1FCXFFSUJFO5A has reached a steady state.
```

5.Load balancer: the external load balancer does have 1 healthy instance on it. 

6. The way I deployed the app is use this command: `emp deploy windweller/nodedockertest:latest` because I hosted my image on Docker hub.

And everything else I followed the tutorial: `http://empire.readthedocs.org/en/latest/quickstart_using/`, nothing went wrong.

**Comment by windweller** [comment]
When I ssh into the AWS instance (I only chose to deploy 1 instance) , and type `docker ps`, I get this:
```
[ec2-user@ip-10-0-1-232 ~]$ docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS                        NAMES
e24d03b6bd8c        remind101/empire:latest          "/go/bin/empire serv   3 days ago          Up 3 days           0.0.0.0:8080->8080/tcp       ecs-empir-TaskD-1EL4OZ8PB9I70-1-empire-b2cfe6a3d3acaa8b9b01
7809b7fce578        postgres:latest                  "/docker-entrypoint.   3 days ago          Up 3 days           0.0.0.0:5432->5432/tcp       ecs-empir-TaskD-1EL4OZ8PB9I70-1-postgres-82bef28ef4a8a8ace601
03a9c89732e3        amazon/amazon-ecs-agent:latest   "/agent"               3 days ago          Up 3 days           127.0.0.1:51678->51678/tcp   ecs-agent
```

Strange enough I don't see my own app at all, maybe this is the reason why?

**Comment by phobologic** [comment]
1. Empire doesn't work with git the same way that heroku does, but it does use a modified version of the hk client - looks like we left the git integration in there.  I've opened this to take care of it: https://github.com/remind101/emp/issues/15

In order to see your processes, you need to provide the -a flag - so : `emp ps -a windweller/nodedockertest`.  Does that report anything?

2. Cool.

3. It does take a Procfile, but it also creates a 'web' process for you from the Dockerfile's CMD statement, so this should be working.

4. Do you see any tasks in the ECS console?  What state are they in?

5. If you have one healthy instance - are you sure you're looking at the app load balancer, or are you looking at the Empire API's load balancer?  What is the load balancer named?

That said, you're going to want more than one server.  You need N+1 servers, where N is the # of instances of your web processes.  The reason for this is that without N+1 (ie, if you want to scale to 4 web processes, you need 5 hosts) you can't do upgrades or even redeploy your code due to limitations in ECS.

**Comment by phobologic** [comment]
Sorry - the command for ps doesn't use the repo name.  I've updated #1 up above.

**Comment by windweller** [comment]
Hmmm, maybe this is indeed the problem:
```
➜  docker-node-hello git:(master) emp ps -a nodedockertest
➜  docker-node-hello git:(master)
```
When I type in `emp ps -a nodedockertest` I get nothing, but `emp apps` is the only thing that's reporting.

For point 4, when I see the ECS console tasks, I see two tasks:
```
11ae017d-23dd-486a-8f4c-6945dfb287a9--web ACTIVE
 
empir-TaskD-1EL4OZ8PB9I70 ACTIVE
```

If I go to the `web` task, here is what I see:
```
Container-Name Image
web windweller/nodedockertest:latest

Command	["node","index.js"]

Port Mappings

Host Port	Container Port	Protocol
9000	8080	tcp

Environment Variables

Key	Value
SOURCE	nodedockertest.v1.web
EMPIRE_RELEASE	v1
EMPIRE_CREATED_AT	2015-07-19T21:30:50Z
PORT	8080
EMPIRE_APPNAME	nodedockertest
EMPIRE_PROCESS	web
```

I'm not familiar enough with ECS, but I'll probably redeploy it and make to 2 instances.

**Comment by phobologic** [comment]
Yeah - something is very wrong there if there are tasks running, but you don't see any in `emp ps`

That said - does the task you see in the ECS console stick around or does it keep dying and getting replaced with a new one?  That could lead to the issues you're seeing.

**Comment by windweller** [comment]
If I go to my cluster, and see the running task:

Cluster : empir-Clust-L19ZHSSESOLC

I see two services running:
 
```
empir-Servi-1FCXFFSUJFO5A ACTIVE empir-TaskD-1EL4OZ8PB9I70:1
desired tasks: 1
running tasks: 1
 
11ae017d-23dd-486a-8f4c-6945dfb287a9--web ACTIVE 11ae017d-23dd-486a-8f4c-6945dfb287a9--web:1
desired tasks: 1
running tasks: 0
```

When I go to the `Task` tab, I see one task running. Maybe this is the problem?

Does it help when I said I SSH into the instance and try `docker ps` and I only see empire docker running not my `nodedockertest` docker running?

**Comment by windweller** [comment]
Hey @phobologic, thank you for helping me debug this issue. Once I change the instance number from 1 to 2, things seem to start working. 

I can now use `emp ps -a containername` command to get the information.

```
➜  docker-node-hello git:(master) emp apps
nodedockertest      Jul 23 18:00
➜  docker-node-hello git:(master) emp ps -a nodedockertest
v1.web.bb1ff7ce-c085-4f9c-adff-96254af3823f  1X  RUNNING   6m  "node index.js"
```

I also find it interesting when I look under the Cluster/Task, and the web task. If you just simply visit `52.2.41.7:9000`, it works. So my only question left is: is this linked with a load balancer? What's the external load balancer that's really set up? Why can't I visit the NodeJS server from there? Do I need to set up a separator ELB to connect to my current 2 instances?

```
web
2903eb14-d39a-4ad9-9be3-24317a7bfa70
RUNNING
windweller/nodedockertest:latest
256
512
true
Details

Entry Point	
Command	["node","index.js"]
Links	
Network Bindings

Host Port	Container Port	Protocol	External Link
9000	8080	tcp	52.2.41.7:9000
Environment Variables

Key	Value
SOURCE	nodedockertest.v1.web
EMPIRE_RELEASE	v1
EMPIRE_CREATED_AT	2015-07-23T22:01:04Z
PORT	8080
EMPIRE_APPNAME	nodedockertest
EMPIRE_PROCESS	web
```

**Comment by phobologic** [comment]
Awesome!  I'm glad that it started working with more instances - we haven't had anyone attempt to run with a single instance, so I have no idea what was going on there.  The fact that you had 1 expected task, and 0 running tasks for the app you were deploying wasn't a great sign.

Now, as far as your other questions - when you release an app in Empire that has a 'web' process (in the Procfile, or if you don't have a Procfile it assumes I believe) it automatically creates a load balancer for you that will be attached to all copies of that process.

In the demo env, because we don't have separate public/private subnets, *all* exposed processes are public through an ELB.

In a production environment, you'd have a public & private subnet, and Minions would live in the private.  By default all deployed applications in Empire will only be private.  To make them public you have to first `emp create`/`emp domain-add`/`emp deploy` - the domain-add tells Empire to make it a public ELB.

All of this will make more sense when we have our public templates out there - which I'm just about to publish, so keep an eye out :)

For now, I'm going to go ahead and close this issue since it's resolved.  You should, if you haven't already, join the empire-dev google group - there's a community there that can help with questions when I'm busy :)

Glad it's working for you!
