### ISSUE TITLE
Support for TCP Load Balancer

### ISSUE THREAD

**Issue by corentone** [remind101/empire#630]
If we can move forward with issue #491 , I would have another suggestion, adding TCP ELB support.
Heroku has the limitation of HTTP(S) but Empire doesn't have to!

One way to do it would be to arbitrarily use a TCP balancer if the port is not a known HTTP(S) port (80, 8080, 591, 8008, 443, ..).

My current workaround is to manually go edit the ELB but that seems hacky :)

**Comment by phobologic** [comment]
Hey @corentone - yeah, that kind of thing is totally part of the ideas we have for the extended procfile support.

One warning about modifying things manually - it can lead to issues with a lot of stuff. You may not be able to add new config variables, or do a release, afterwards because there's a mismatch in what Empire thinks the ELB should look like vs what it really looks like.

See #627 for an example of what can go wrong.

**Comment by diranged** [comment]
This is actually a blocker for us -- we use a ton of ELBs in tcp mode so that we can use raw ask for authentication of backend systems.

Strong :+1: here!

**Comment by ejholmes** [comment]
This was merged into master, and will be supported in the 0.12.0 release of Empire! Doc updates are currently in a PR at https://github.com/remind101/empire/pull/1006
