### ISSUE TITLE
Add support for docker-compose.yml

### ISSUE THREAD

**Issue by rodlogic** [remind101/empire#637]
It would be nice to be able to deploy full apps with docker-compose.yml

**Comment by phobologic** [comment]
I'm not sure if this is best for empire itself, or a separate command that made use of the empire API.  Going to leave this open for more discussion - though there are probably a few mismatches between docker-compose & empire's style of deployments.

**Comment by rodlogic** [comment]
By separate command you mean some sort of empire plugin (sorry, I am fairly new to empire)? I have also been taking a look at convox and it is quite nice the way they to keep the interface simple by leveraging docker-compose.yml. Empire seems to be much more mature as far as I can see.

**Comment by phobologic** [comment]
Well, I could see it more like this relationship:

emp/empire -> docker
*some other command* -> docker-compose

So empire & the emp CLI are meant for the heroku style deployments that it currently does.  But there could be a new command, a sort of orchestration command, that does what docker-compose does for docker, but in an empire environment.

convox is awesome - one downside to the docker-compose interface being the main interface is that you can't scale individual processes in a project by themselves (there are ways around this, I think - not sure if you can have more than one docker-compose).  For example, in our API app @remind, we have workers & we have web processes.  We need way more web processes than workers, and there is no reason they should/need to be co-located.  Since all of that is separate in Empire, we can scale them independently - I think we have like 12 web processes and only 6 workers.

**Comment by rodlogic** [comment]
@phobologic Yes, that is a good point.

**Comment by rodlogic** [comment]
@phobologic One idea would be to use docker-composer (docker) labels to tag specific containers and then have deployment configuration parameters that are specific to those tags. Another idea is to reference a specific container: so if there is an docker-compose.yml for app1 and a web container, it should/could be possible to scale app1.web independently.

**Comment by phobologic** [comment]
Yeah - my biggest concern with making it a core part of the emp CLI and not it's own tool is that it complicates the emp CLI.  Using docker-compose.yml isn't impossible.  Just not sure it's exactly the right format we would want or if it's the best for the project.  Anyway, it's not something that we're likely to work on for a bit - there's a lot of core stuff to focus on soon, but it sounds like a cool, perhaps complicated project :)

**Comment by rodlogic** [comment]
@phobologic got it!

**Comment by ejholmes** [comment]
Gonna close this for now. If someone submits a PR that adds support for docker-compose.yml files, we'll consider accepting it.
