### ISSUE TITLE
Environment variable needed to print version.

### ISSUE THREAD

**Issue by zabawaba99** [remind101/empire#673]
Is it necessary to specify environment variables to print the version?

```bash
~ emp version
error: EMPIRE_API_URL must be set
```

**Comment by ejholmes** [comment]
The http client gets initialized for [every command in the `emp`](https://github.com/remind101/emp/blob/02b314f1ede6ad90c6a9a833ace5a33a01671f1a/hkclient/client.go#L24-L27). You can easily get around this by setting EMPIRE_API_URL to some bogus value.

I'm going to close this here since it's a client problem. Feel free to re-open on https://github.com/remind101/emp/issues.

**Comment by zabawaba99** [comment]
My apologies. I thought I had opened it under emp.
