### ISSUE TITLE
Unable to find tasks or services easily in ECS console

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#684]
We have 20+ services running on empire, and have been having some issues where old deploys hang around for hours. 

I'm trying to work out if it's an issue with ECS or empire, but I can't see any way of finding the service in question without having to go into every single service that's running, open a task definition and then look at which docker image it's related to.

Is there an easier way to quickly link an app or task for an app from the emp command line with the appropriate part in ECS?

**Comment by crohr** [comment]
What I found is that you can `emp info -a service`, take the UUID returned, and use that to filter tasks in the ECS cluster. But it's still a bit clumsy.

**Comment by benguillet** [comment]
Hey @gileze33, tasks definitions and services are named on ECS after the Empire app id and the process type, so all you have to do is get the app id from the deploy hanging with `emp info -a <app>`

**Comment by rgabo** [comment]
@benguillet can you list what you believe are benefits to naming services/task definitions after the Empire app id instead of the a more human-readable naming convention?

The cryptic naming has been killing us when it comes to looking at ELB, ECS and when looking at monitoring/metrics in Datadog and New Relic. It's not that we can build tooling around it, but it is unnecessary complexity.

Thanks!

**Comment by ejholmes** [comment]
Couple of reasons we decided to use the app id instead of the name (which
we used initially):

1. To support renaming. Keying everything off the unique app id means we
have to change less in aws if the app name changes. Granted we don't
support `emp rename` right now, it's still leaves things open for it.
2. We ran into a lot of bugs/issues when deleting an ECS service and
re-creating a new one of the same name (e.g. `emp destroy && emp deploy`).
Mainly the ECS service getting stuck in a drainig state indefinitely.
Always using a unique identifier got around this.

Our hope was that ECS would eventually support tags, but that hasn't
happened yet, so it does add some annoyance. We've felt it too, although it
hasn't been painful enough for us to warrant going back to using app name
(and the migration involved in that).

Eventually, I'd like to use CloudFormation to provision the apps resources
instead of talking to ECS/ELB/Route53 directly, which would solve most of
these issues. No time frame on that though.

**Comment by rgabo** [comment]
thanks for the explanation @ejholmes, we have high hopes for Docker/ECS tags as well.

Are pluggable provisioning backends (such as the CloudFormation-based you mentioned) at least on the roadmap? :wink: If the interfaces were defined, we'd be happy to contribute an implementation for Swarm to reduce our reliance on ECS. You can keep us in mind if you start looking into it.

**Comment by ejholmes** [comment]
@rgabo technically, it's already supported through the [scheduler.Scheduler](https://github.com/remind101/empire/blob/master/scheduler/scheduler.go#L117-L133) interface. There's a stubbed out [docker](https://github.com/remind101/empire/tree/master/scheduler/docker) implementation.

In the long run, I was thinking it would be good to pull out the `scheduler` package into it's own project, since it's basically a package for running 12factor applications with some backend (ECS/Kubernetes/Docker/Nomad/etc). I started some work on that [here](https://github.com/ejholmes/12factor)

**Comment by rgabo** [comment]
@ejholmes cool, thanks for pointing that out. The `docker` implementation is interesting for us in the long term as it could be served by Swarm. I'll let you know if we decide to work on this.

**Comment by ejholmes** [comment]
@rgabo agreed. Lemme know if you need any help with it. I think it could be a little challenging, because swarm is essentially a level of abstraction below ECS/Kubernetes, since it doesn't have the concept of horizontal scalability built in. Maybe [libcompose](https://github.com/docker/libcompose) could be used.

**Comment by gileze33** [comment]
Quick thought as I ran into this again earlier - what are the IDs in the output of `emp ps`? 

Could these potentially include the ECS task IDs?

**Comment by ejholmes** [comment]
@gileze33 yes. The uuids you see in the output of `emp ps` are ECS task ids.

**Comment by mhahn** [comment]
Is there a reason we can't do something like this:

`<uuid>--<app-name>--<process-name>`?

**Comment by ejholmes** [comment]
@mhahn that's fine if we never support an `emp rename`, which I think is reasonable. We've never really felt the need to rename an app, and we'd probably just re-create it anyway.

**Comment by brianz** [comment]
I like the having the app name as proposed by @mhahn.  Not having a rename sounds like a fine compromise.

**Comment by ejholmes** [comment]
For those that come across this, in the next release of Empire (0.11.0), it manages AWS resources via CloudFormation stacks, so the resources are named based on the stack name (which is just the app name), making it much easier to find resources.
