### ISSUE TITLE
Support logConfiguration for ECS Task Definitions

### ISSUE THREAD

**Issue by brianz** [remind101/empire#704]
I'm looking into getting application logs into Loggly or some other hosted system.  Now, I think my ideal solution would use Docker's `syslog` driver to send application logs to the host where I'd then run a daemon to pick those up and ship them.  This design can be extended to any hosted system:

```
container app logs -> stdout -> host syslog -> wherever (Loggly, etc.)...totally configurable
```

One option for logs is https://github.com/gliderlabs/logspout suggested by @phobologic, however that has some limitations AFAICT:

- have to run another container on every Empire minion (arguably not a huge deal)
- can't ship to host's syslog (see https://github.com/gliderlabs/logspout/issues/118 ...bigger deal)

ECS Task Definitions support configuration for the `log_driver` and `log_opts` options:

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#ContainerDefinition-logConfiguration

I *think* this would be the place to hook into the AWS API to set these options:

https://github.com/remind101/empire/blob/master/pkg/ecsutil/client.go#L60

Which I think is called from the scheduler:

https://github.com/remind101/empire/blob/master/scheduler/ecs/ecs.go#L343

I think there may be some repercussions from setting the `log_driver`, however I think the solution above would be really nice since it puts the owner of the Empire minion in full control over what happens to logs without needing to introduce another moving part.

**Comment by phobologic** [comment]
So the big issue with this is that docker only allows a single log driver to be defined, and when you define anything but `json-file` or `journald` it disables `docker logs`/the api for streaming logs.  That will effectively break the `emp log` functionality.  Not sure if that's ok.

Regarding the logspout limitations - I think the first limitation isn't real, since empire already runs logspout, so it'd just involve modifying that configuration.  The second issue is a bit harder to deal with - largely due to needing to figure out what 'localhost' is for the host your docker containers are running on.  We ran into this when we started running statsd on our hosts, and resolved it with a local dnsmasq, though that is a little complicated.

WE've also talked about figuring out a way to hard code the `docker0` bridge IP (it seems to be the same on all our hosts, so this may not be necessary, but we haven't had a chance to dig into it yet to verify), then you can just configure all your daemons to talk to syslog via the network on that IP.

**Comment by brianz** [comment]
It'd good to know that the Empire AMI runs logspout out of the box:

https://github.com/remind101/empire_ami/tree/master/ansible/roles/logspout

However, we're building our own AMI and don't run that currently.  I don't think it's a huge deal to add it but there is the limitation in getting it to talk to the Docker host which we both mentioned.

I still see a lot of advantages in adding the ability to control `logConfiguration` from Empire.  Even if sticking with the default `json-file` log it'd be possible to tag logs per application (via `log-opt`) and control it in any way which is useful for the user.

**Comment by ejholmes** [comment]
@brianz using `logConfiguration` in the ECS api's would definitely be the best long term goal, but like @phobologic said, there's a lot of little nuances (mostly around being able to segregate logs per application rather than per container). Logspout isn't great for a lot of reasons, mostly because it "pulls" logs out of the docker daemon.

I think it would be better if Empire just set the log configuration to send logs over syslog to 514 on the host, and then you can run whatever you want on that port to forward it somewhere else.

**Comment by brianz** [comment]
Indeed, I'm sure there are plenty of nuances I'm not thinking about or just don't know to consider with this.

> I think it would be better if Empire just set the log configuration to send logs over syslog to 514 on the host

So, are you suggesting that, rather than supporting control of logConfiguration from Empire it would instead simply use `--log-driver=syslog` by default?  I'd be +1 on that approach since it doesn't break any existing functionality AFAIK and gives the end-user complete access and control of the logs from the host OS.

**Comment by ejholmes** [comment]
@brianz pretty much, or at the very least, make logConfiguration a configuration option you pass when you start up Empire.

**Comment by baversjo** [comment]
Just reading from the logspout documentation, it seems a standard option is to "Route all container output to remote syslog". Both loggly and papertrailapp supports this directly. For added security, I could also see specifying a local server in your VPC as the remote syslog, and then let that server be responsible for sending logs to an external service.

All we'd need to do is to add a configuration option to empire allowing you to specify a syslog target for logspout? I'd be happy to do this if it sounds like a good (at least short term) approach.

**Comment by brianz** [comment]
Closing this with the change in 034890a8b0e59883d184dd44b14009a1625919f8

Empire can now be set to log to `json-file` or `syslog` by passing either to the `--ecs.logdriver` cli argument.  Use zero or more `--ecs.logopt` field to control the options.  These are all passed verbatim to ECS / Docker.
