### ISSUE TITLE
EOF errors when making large changes

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#770]
While scaling all processes down to 0 while doing some maintenance (and then scaling back up after the maintenance), after hanging for a bit, I eventually got an `EOF` error.  My guess is that this is due to the ELB timing out since no data is being sent back to the client.

It also makes it hard to tell which apps were scaled down and which weren't, so you have to check on that and then re-run the truncated command.

```
# emp scale -a acme-inc proc1=1:1X proc2=1:1X proc3=1:2X proc4=1:2X proc5=1:2X proc6=6:1024:1.00gb proc7=20:1X proc8=1:512:6.00gb web=25:PX
error: EOF
```

Also, the next couple of replies get an error from ECS due to limited #'s of deployments.  Not sure there's really anything that can be done about that though, other than wait for the existing deployments to finish:

```
error: InvalidParameterException: 5 active deployments exist, unable to create new deployment.
    status code: 400, request id: ae119f19-eb41-11e5-a4dc-0f01aa337913
```

**Comment by ejholmes** [comment]
I was just thinking about this, and ended up digging into how Go handles TCP keep alives by default. Turns out, any accepted TCP connections from `http.Server` get [TCP keepalives enabled](https://golang.org/src/net/http/server.go?s=64484:64531#L2426), but the [TCP_KEEPINTVL](http://man7.org/linux/man-pages/man7/tcp.7.html) option is set to 3 minutes (we set a 60 second idle connection timeout).

If we increased the idle connection timeout to something like 4 minutes, this might help, although, we'd also need to enable keep alives from the client connection as well.
