### ISSUE TITLE
emp run doesn't accept custom sizes like emp scale

### ISSUE THREAD

**Issue by iserko** [remind101/empire#986]
Was hoping to be able to specify a custom CPU:MEMORY size when doing `emp run`, but it appears that's not possible:

https://github.com/remind101/empire/blob/3ef4bab4ceaedfb3d56d9ddc14f8359921d1354d/cmd/emp/run.go#L100

`emp run -a app_name -s PX bash` works
`emp run -a app_name -s 512:3GB bash` is what I would like to see work

Use case for this is that we need to run a script which uses more memory than the web container (about 4 times as much). We could specify PX as the size, but that's too much of a strain on the cluster, for no good reason. If we did that we'd need to start a new node just for this script.

**Comment by ejholmes** [comment]
Right, I believe this is only a client side issue (which we inherited from forking hk), since the server parses using the same [empire.Constraints](https://github.com/remind101/empire/blob/184a9101ed54cbfbcd2c83024344b8021f6f7b36/server/heroku/processes.go#L61) type. I think we should basically just remove that line.
